// Code generated by MockGen. DO NOT EDIT.
// Source: drawal.go
//
// Generated by this command:
//
//	mockgen -source=drawal.go -destination=mocks/drawal_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	drawal "kialkuz/shop-with-loyalty/internal/domain/drawal/dto"
	model "kialkuz/shop-with-loyalty/internal/domain/drawal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockDrawalRepository is a mock of DrawalRepository interface.
type MockDrawalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDrawalRepositoryMockRecorder
	isgomock struct{}
}

// MockDrawalRepositoryMockRecorder is the mock recorder for MockDrawalRepository.
type MockDrawalRepositoryMockRecorder struct {
	mock *MockDrawalRepository
}

// NewMockDrawalRepository creates a new mock instance.
func NewMockDrawalRepository(ctrl *gomock.Controller) *MockDrawalRepository {
	mock := &MockDrawalRepository{ctrl: ctrl}
	mock.recorder = &MockDrawalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDrawalRepository) EXPECT() *MockDrawalRepositoryMockRecorder {
	return m.recorder
}

// AddTx mocks base method.
func (m *MockDrawalRepository) AddTx(ctx context.Context, tx pgx.Tx, arg2 model.Drawal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTx", ctx, tx, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTx indicates an expected call of AddTx.
func (mr *MockDrawalRepositoryMockRecorder) AddTx(ctx, tx, arg2 any) *MockDrawalRepositoryAddTxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTx", reflect.TypeOf((*MockDrawalRepository)(nil).AddTx), ctx, tx, arg2)
	return &MockDrawalRepositoryAddTxCall{Call: call}
}

// MockDrawalRepositoryAddTxCall wrap *gomock.Call
type MockDrawalRepositoryAddTxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrawalRepositoryAddTxCall) Return(arg0 error) *MockDrawalRepositoryAddTxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrawalRepositoryAddTxCall) Do(f func(context.Context, pgx.Tx, model.Drawal) error) *MockDrawalRepositoryAddTxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrawalRepositoryAddTxCall) DoAndReturn(f func(context.Context, pgx.Tx, model.Drawal) error) *MockDrawalRepositoryAddTxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByUserID mocks base method.
func (m *MockDrawalRepository) GetByUserID(ctx context.Context, userID uuid.UUID) ([]drawal.UserDrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]drawal.UserDrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockDrawalRepositoryMockRecorder) GetByUserID(ctx, userID any) *MockDrawalRepositoryGetByUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockDrawalRepository)(nil).GetByUserID), ctx, userID)
	return &MockDrawalRepositoryGetByUserIDCall{Call: call}
}

// MockDrawalRepositoryGetByUserIDCall wrap *gomock.Call
type MockDrawalRepositoryGetByUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrawalRepositoryGetByUserIDCall) Return(arg0 []drawal.UserDrawal, arg1 error) *MockDrawalRepositoryGetByUserIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrawalRepositoryGetByUserIDCall) Do(f func(context.Context, uuid.UUID) ([]drawal.UserDrawal, error)) *MockDrawalRepositoryGetByUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrawalRepositoryGetByUserIDCall) DoAndReturn(f func(context.Context, uuid.UUID) ([]drawal.UserDrawal, error)) *MockDrawalRepositoryGetByUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
