// Code generated by MockGen. DO NOT EDIT.
// Source: balance.go
//
// Generated by this command:
//
//	mockgen -source=balance.go -destination=mocks/balance_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "kialkuz/shop-with-loyalty/internal/modules/balance/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceRepository is a mock of BalanceRepository interface.
type MockBalanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepositoryMockRecorder
	isgomock struct{}
}

// MockBalanceRepositoryMockRecorder is the mock recorder for MockBalanceRepository.
type MockBalanceRepositoryMockRecorder struct {
	mock *MockBalanceRepository
}

// NewMockBalanceRepository creates a new mock instance.
func NewMockBalanceRepository(ctrl *gomock.Controller) *MockBalanceRepository {
	mock := &MockBalanceRepository{ctrl: ctrl}
	mock.recorder = &MockBalanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepository) EXPECT() *MockBalanceRepositoryMockRecorder {
	return m.recorder
}

// AddTx mocks base method.
func (m *MockBalanceRepository) AddTx(ctx context.Context, tx pgx.Tx, balance model.Balance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTx", ctx, tx, balance)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTx indicates an expected call of AddTx.
func (mr *MockBalanceRepositoryMockRecorder) AddTx(ctx, tx, balance any) *MockBalanceRepositoryAddTxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTx", reflect.TypeOf((*MockBalanceRepository)(nil).AddTx), ctx, tx, balance)
	return &MockBalanceRepositoryAddTxCall{Call: call}
}

// MockBalanceRepositoryAddTxCall wrap *gomock.Call
type MockBalanceRepositoryAddTxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBalanceRepositoryAddTxCall) Return(arg0 error) *MockBalanceRepositoryAddTxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBalanceRepositoryAddTxCall) Do(f func(context.Context, pgx.Tx, model.Balance) error) *MockBalanceRepositoryAddTxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBalanceRepositoryAddTxCall) DoAndReturn(f func(context.Context, pgx.Tx, model.Balance) error) *MockBalanceRepositoryAddTxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByUserID mocks base method.
func (m *MockBalanceRepository) GetByUserID(ctx context.Context, userID uuid.UUID) (*model.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockBalanceRepositoryMockRecorder) GetByUserID(ctx, userID any) *MockBalanceRepositoryGetByUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockBalanceRepository)(nil).GetByUserID), ctx, userID)
	return &MockBalanceRepositoryGetByUserIDCall{Call: call}
}

// MockBalanceRepositoryGetByUserIDCall wrap *gomock.Call
type MockBalanceRepositoryGetByUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBalanceRepositoryGetByUserIDCall) Return(arg0 *model.Balance, arg1 error) *MockBalanceRepositoryGetByUserIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBalanceRepositoryGetByUserIDCall) Do(f func(context.Context, uuid.UUID) (*model.Balance, error)) *MockBalanceRepositoryGetByUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBalanceRepositoryGetByUserIDCall) DoAndReturn(f func(context.Context, uuid.UUID) (*model.Balance, error)) *MockBalanceRepositoryGetByUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByUserIDWithBlockForUpdate mocks base method.
func (m *MockBalanceRepository) GetByUserIDWithBlockForUpdate(ctx context.Context, tx pgx.Tx, userID uuid.UUID) (*model.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserIDWithBlockForUpdate", ctx, tx, userID)
	ret0, _ := ret[0].(*model.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserIDWithBlockForUpdate indicates an expected call of GetByUserIDWithBlockForUpdate.
func (mr *MockBalanceRepositoryMockRecorder) GetByUserIDWithBlockForUpdate(ctx, tx, userID any) *MockBalanceRepositoryGetByUserIDWithBlockForUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserIDWithBlockForUpdate", reflect.TypeOf((*MockBalanceRepository)(nil).GetByUserIDWithBlockForUpdate), ctx, tx, userID)
	return &MockBalanceRepositoryGetByUserIDWithBlockForUpdateCall{Call: call}
}

// MockBalanceRepositoryGetByUserIDWithBlockForUpdateCall wrap *gomock.Call
type MockBalanceRepositoryGetByUserIDWithBlockForUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBalanceRepositoryGetByUserIDWithBlockForUpdateCall) Return(arg0 *model.Balance, arg1 error) *MockBalanceRepositoryGetByUserIDWithBlockForUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBalanceRepositoryGetByUserIDWithBlockForUpdateCall) Do(f func(context.Context, pgx.Tx, uuid.UUID) (*model.Balance, error)) *MockBalanceRepositoryGetByUserIDWithBlockForUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBalanceRepositoryGetByUserIDWithBlockForUpdateCall) DoAndReturn(f func(context.Context, pgx.Tx, uuid.UUID) (*model.Balance, error)) *MockBalanceRepositoryGetByUserIDWithBlockForUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByUsersID mocks base method.
func (m *MockBalanceRepository) GetByUsersID(ctx context.Context, usersID []uuid.UUID) (map[uuid.UUID]model.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsersID", ctx, usersID)
	ret0, _ := ret[0].(map[uuid.UUID]model.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsersID indicates an expected call of GetByUsersID.
func (mr *MockBalanceRepositoryMockRecorder) GetByUsersID(ctx, usersID any) *MockBalanceRepositoryGetByUsersIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsersID", reflect.TypeOf((*MockBalanceRepository)(nil).GetByUsersID), ctx, usersID)
	return &MockBalanceRepositoryGetByUsersIDCall{Call: call}
}

// MockBalanceRepositoryGetByUsersIDCall wrap *gomock.Call
type MockBalanceRepositoryGetByUsersIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBalanceRepositoryGetByUsersIDCall) Return(arg0 map[uuid.UUID]model.Balance, arg1 error) *MockBalanceRepositoryGetByUsersIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBalanceRepositoryGetByUsersIDCall) Do(f func(context.Context, []uuid.UUID) (map[uuid.UUID]model.Balance, error)) *MockBalanceRepositoryGetByUsersIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBalanceRepositoryGetByUsersIDCall) DoAndReturn(f func(context.Context, []uuid.UUID) (map[uuid.UUID]model.Balance, error)) *MockBalanceRepositoryGetByUsersIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTx mocks base method.
func (m *MockBalanceRepository) UpdateTx(ctx context.Context, tx pgx.Tx, balance model.Balance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTx", ctx, tx, balance)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTx indicates an expected call of UpdateTx.
func (mr *MockBalanceRepositoryMockRecorder) UpdateTx(ctx, tx, balance any) *MockBalanceRepositoryUpdateTxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTx", reflect.TypeOf((*MockBalanceRepository)(nil).UpdateTx), ctx, tx, balance)
	return &MockBalanceRepositoryUpdateTxCall{Call: call}
}

// MockBalanceRepositoryUpdateTxCall wrap *gomock.Call
type MockBalanceRepositoryUpdateTxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBalanceRepositoryUpdateTxCall) Return(arg0 error) *MockBalanceRepositoryUpdateTxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBalanceRepositoryUpdateTxCall) Do(f func(context.Context, pgx.Tx, model.Balance) error) *MockBalanceRepositoryUpdateTxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBalanceRepositoryUpdateTxCall) DoAndReturn(f func(context.Context, pgx.Tx, model.Balance) error) *MockBalanceRepositoryUpdateTxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
