// Code generated by MockGen. DO NOT EDIT.
// Source: transaction_manager.go
//
// Generated by this command:
//
//	mockgen -source=transaction_manager.go -destination=mocks/transaction_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
	isgomock struct{}
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// RunTransaction mocks base method.
func (m *MockTransaction) RunTransaction(ctx context.Context, fn func(pgx.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransaction indicates an expected call of RunTransaction.
func (mr *MockTransactionMockRecorder) RunTransaction(ctx, fn any) *MockTransactionRunTransactionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransaction", reflect.TypeOf((*MockTransaction)(nil).RunTransaction), ctx, fn)
	return &MockTransactionRunTransactionCall{Call: call}
}

// MockTransactionRunTransactionCall wrap *gomock.Call
type MockTransactionRunTransactionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTransactionRunTransactionCall) Return(arg0 error) *MockTransactionRunTransactionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTransactionRunTransactionCall) Do(f func(context.Context, func(pgx.Tx) error) error) *MockTransactionRunTransactionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTransactionRunTransactionCall) DoAndReturn(f func(context.Context, func(pgx.Tx) error) error) *MockTransactionRunTransactionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
