// Code generated by MockGen. DO NOT EDIT.
// Source: kialkuz/shop-with-loyalty/internal/contracts/repository (interfaces: AuthRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/auth_repository_mock.go -package=mocks -typed kialkuz/shop-with-loyalty/internal/contracts/repository AuthRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "kialkuz/shop-with-loyalty/internal/model"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// AddNewToken mocks base method.
func (m *MockAuthRepository) AddNewToken(ctx context.Context, token model.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewToken indicates an expected call of AddNewToken.
func (mr *MockAuthRepositoryMockRecorder) AddNewToken(ctx, token any) *MockAuthRepositoryAddNewTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewToken", reflect.TypeOf((*MockAuthRepository)(nil).AddNewToken), ctx, token)
	return &MockAuthRepositoryAddNewTokenCall{Call: call}
}

// MockAuthRepositoryAddNewTokenCall wrap *gomock.Call
type MockAuthRepositoryAddNewTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthRepositoryAddNewTokenCall) Return(arg0 error) *MockAuthRepositoryAddNewTokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthRepositoryAddNewTokenCall) Do(f func(context.Context, model.Token) error) *MockAuthRepositoryAddNewTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthRepositoryAddNewTokenCall) DoAndReturn(f func(context.Context, model.Token) error) *MockAuthRepositoryAddNewTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddNewTokenTx mocks base method.
func (m *MockAuthRepository) AddNewTokenTx(ctx context.Context, tx pgx.Tx, token model.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewTokenTx", ctx, tx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewTokenTx indicates an expected call of AddNewTokenTx.
func (mr *MockAuthRepositoryMockRecorder) AddNewTokenTx(ctx, tx, token any) *MockAuthRepositoryAddNewTokenTxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewTokenTx", reflect.TypeOf((*MockAuthRepository)(nil).AddNewTokenTx), ctx, tx, token)
	return &MockAuthRepositoryAddNewTokenTxCall{Call: call}
}

// MockAuthRepositoryAddNewTokenTxCall wrap *gomock.Call
type MockAuthRepositoryAddNewTokenTxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthRepositoryAddNewTokenTxCall) Return(arg0 error) *MockAuthRepositoryAddNewTokenTxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthRepositoryAddNewTokenTxCall) Do(f func(context.Context, pgx.Tx, model.Token) error) *MockAuthRepositoryAddNewTokenTxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthRepositoryAddNewTokenTxCall) DoAndReturn(f func(context.Context, pgx.Tx, model.Token) error) *MockAuthRepositoryAddNewTokenTxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
