// Code generated by MockGen. DO NOT EDIT.
// Source: order.go
//
// Generated by this command:
//
//	mockgen -source=order.go -destination=mocks/order_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "kialkuz/shop-with-loyalty/internal/modules/order/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockOrderRepository) Add(ctx context.Context, order model.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockOrderRepositoryMockRecorder) Add(ctx, order any) *MockOrderRepositoryAddCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockOrderRepository)(nil).Add), ctx, order)
	return &MockOrderRepositoryAddCall{Call: call}
}

// MockOrderRepositoryAddCall wrap *gomock.Call
type MockOrderRepositoryAddCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryAddCall) Return(arg0 error) *MockOrderRepositoryAddCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryAddCall) Do(f func(context.Context, model.Order) error) *MockOrderRepositoryAddCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryAddCall) DoAndReturn(f func(context.Context, model.Order) error) *MockOrderRepositoryAddCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByNumber mocks base method.
func (m *MockOrderRepository) GetByNumber(ctx context.Context, number string) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNumber", ctx, number)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNumber indicates an expected call of GetByNumber.
func (mr *MockOrderRepositoryMockRecorder) GetByNumber(ctx, number any) *MockOrderRepositoryGetByNumberCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNumber", reflect.TypeOf((*MockOrderRepository)(nil).GetByNumber), ctx, number)
	return &MockOrderRepositoryGetByNumberCall{Call: call}
}

// MockOrderRepositoryGetByNumberCall wrap *gomock.Call
type MockOrderRepositoryGetByNumberCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryGetByNumberCall) Return(arg0 *model.Order, arg1 error) *MockOrderRepositoryGetByNumberCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryGetByNumberCall) Do(f func(context.Context, string) (*model.Order, error)) *MockOrderRepositoryGetByNumberCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryGetByNumberCall) DoAndReturn(f func(context.Context, string) (*model.Order, error)) *MockOrderRepositoryGetByNumberCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByUserID mocks base method.
func (m *MockOrderRepository) GetByUserID(ctx context.Context, userID uuid.UUID) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockOrderRepositoryMockRecorder) GetByUserID(ctx, userID any) *MockOrderRepositoryGetByUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockOrderRepository)(nil).GetByUserID), ctx, userID)
	return &MockOrderRepositoryGetByUserIDCall{Call: call}
}

// MockOrderRepositoryGetByUserIDCall wrap *gomock.Call
type MockOrderRepositoryGetByUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryGetByUserIDCall) Return(arg0 []model.Order, arg1 error) *MockOrderRepositoryGetByUserIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryGetByUserIDCall) Do(f func(context.Context, uuid.UUID) ([]model.Order, error)) *MockOrderRepositoryGetByUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryGetByUserIDCall) DoAndReturn(f func(context.Context, uuid.UUID) ([]model.Order, error)) *MockOrderRepositoryGetByUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOrdersForGetAccrual mocks base method.
func (m *MockOrderRepository) GetOrdersForGetAccrual(ctx context.Context) (map[string]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersForGetAccrual", ctx)
	ret0, _ := ret[0].(map[string]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersForGetAccrual indicates an expected call of GetOrdersForGetAccrual.
func (mr *MockOrderRepositoryMockRecorder) GetOrdersForGetAccrual(ctx any) *MockOrderRepositoryGetOrdersForGetAccrualCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersForGetAccrual", reflect.TypeOf((*MockOrderRepository)(nil).GetOrdersForGetAccrual), ctx)
	return &MockOrderRepositoryGetOrdersForGetAccrualCall{Call: call}
}

// MockOrderRepositoryGetOrdersForGetAccrualCall wrap *gomock.Call
type MockOrderRepositoryGetOrdersForGetAccrualCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryGetOrdersForGetAccrualCall) Return(arg0 map[string]model.Order, arg1 error) *MockOrderRepositoryGetOrdersForGetAccrualCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryGetOrdersForGetAccrualCall) Do(f func(context.Context) (map[string]model.Order, error)) *MockOrderRepositoryGetOrdersForGetAccrualCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryGetOrdersForGetAccrualCall) DoAndReturn(f func(context.Context) (map[string]model.Order, error)) *MockOrderRepositoryGetOrdersForGetAccrualCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTx mocks base method.
func (m *MockOrderRepository) UpdateTx(ctx context.Context, tx pgx.Tx, order model.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTx", ctx, tx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTx indicates an expected call of UpdateTx.
func (mr *MockOrderRepositoryMockRecorder) UpdateTx(ctx, tx, order any) *MockOrderRepositoryUpdateTxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTx", reflect.TypeOf((*MockOrderRepository)(nil).UpdateTx), ctx, tx, order)
	return &MockOrderRepositoryUpdateTxCall{Call: call}
}

// MockOrderRepositoryUpdateTxCall wrap *gomock.Call
type MockOrderRepositoryUpdateTxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryUpdateTxCall) Return(arg0 error) *MockOrderRepositoryUpdateTxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryUpdateTxCall) Do(f func(context.Context, pgx.Tx, model.Order) error) *MockOrderRepositoryUpdateTxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryUpdateTxCall) DoAndReturn(f func(context.Context, pgx.Tx, model.Order) error) *MockOrderRepositoryUpdateTxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
