// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -source=user.go -destination=mocks/user_repository_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "kialkuz/shop-with-loyalty/internal/modules/user/model"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AddNewUser mocks base method.
func (m *MockUserRepository) AddNewUser(ctx context.Context, user model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewUser indicates an expected call of AddNewUser.
func (mr *MockUserRepositoryMockRecorder) AddNewUser(ctx, user any) *MockUserRepositoryAddNewUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewUser", reflect.TypeOf((*MockUserRepository)(nil).AddNewUser), ctx, user)
	return &MockUserRepositoryAddNewUserCall{Call: call}
}

// MockUserRepositoryAddNewUserCall wrap *gomock.Call
type MockUserRepositoryAddNewUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryAddNewUserCall) Return(arg0 error) *MockUserRepositoryAddNewUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryAddNewUserCall) Do(f func(context.Context, model.User) error) *MockUserRepositoryAddNewUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryAddNewUserCall) DoAndReturn(f func(context.Context, model.User) error) *MockUserRepositoryAddNewUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddTx mocks base method.
func (m *MockUserRepository) AddTx(ctx context.Context, tx pgx.Tx, user model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTx", ctx, tx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTx indicates an expected call of AddTx.
func (mr *MockUserRepositoryMockRecorder) AddTx(ctx, tx, user any) *MockUserRepositoryAddTxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTx", reflect.TypeOf((*MockUserRepository)(nil).AddTx), ctx, tx, user)
	return &MockUserRepositoryAddTxCall{Call: call}
}

// MockUserRepositoryAddTxCall wrap *gomock.Call
type MockUserRepositoryAddTxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryAddTxCall) Return(arg0 error) *MockUserRepositoryAddTxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryAddTxCall) Do(f func(context.Context, pgx.Tx, model.User) error) *MockUserRepositoryAddTxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryAddTxCall) DoAndReturn(f func(context.Context, pgx.Tx, model.User) error) *MockUserRepositoryAddTxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CheckExistLogin mocks base method.
func (m *MockUserRepository) CheckExistLogin(ctx context.Context, login string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistLogin", ctx, login)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistLogin indicates an expected call of CheckExistLogin.
func (mr *MockUserRepositoryMockRecorder) CheckExistLogin(ctx, login any) *MockUserRepositoryCheckExistLoginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistLogin", reflect.TypeOf((*MockUserRepository)(nil).CheckExistLogin), ctx, login)
	return &MockUserRepositoryCheckExistLoginCall{Call: call}
}

// MockUserRepositoryCheckExistLoginCall wrap *gomock.Call
type MockUserRepositoryCheckExistLoginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryCheckExistLoginCall) Return(arg0 bool, arg1 error) *MockUserRepositoryCheckExistLoginCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryCheckExistLoginCall) Do(f func(context.Context, string) (bool, error)) *MockUserRepositoryCheckExistLoginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryCheckExistLoginCall) DoAndReturn(f func(context.Context, string) (bool, error)) *MockUserRepositoryCheckExistLoginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByLogin mocks base method.
func (m *MockUserRepository) GetByLogin(ctx context.Context, login string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLogin", ctx, login)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLogin indicates an expected call of GetByLogin.
func (mr *MockUserRepositoryMockRecorder) GetByLogin(ctx, login any) *MockUserRepositoryGetByLoginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLogin", reflect.TypeOf((*MockUserRepository)(nil).GetByLogin), ctx, login)
	return &MockUserRepositoryGetByLoginCall{Call: call}
}

// MockUserRepositoryGetByLoginCall wrap *gomock.Call
type MockUserRepositoryGetByLoginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryGetByLoginCall) Return(arg0 *model.User, arg1 error) *MockUserRepositoryGetByLoginCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryGetByLoginCall) Do(f func(context.Context, string) (*model.User, error)) *MockUserRepositoryGetByLoginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryGetByLoginCall) DoAndReturn(f func(context.Context, string) (*model.User, error)) *MockUserRepositoryGetByLoginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
